### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Pcdejong** [datalogic/datalogic.github.io#4]
Small Typo Andorid SDK instead of Android SDK in the sidebar left on top.

![image](https://user-images.githubusercontent.com/19608668/70050803-1b158f00-15d0-11ea-9746-e5902171d00d.png)

**Comment by codybrookshear** [comment]
Hi,
I'm not sure when this was fixed exactly, but looks like this has been corrected:
https://datalogic.github.io/android/overview

Thanks!
Cody
